#!/usr/bin/env ruby

require "aws-sdk"

APPS_TO_DELETE = [
"continuous-delivery-test-docker-app-dev",
"continuous-delivery-test-ruby-ap-dev",
"continuous-delivery-test-ruby-app-dev",
"crx-dev",
"crx-stage",
"davebrandt-paas-tutorial-dev",
"dmc-db-dmc-ws-dev",
"dps-s3generate-dev",
"drautb-pd-badges-frontend-server",
"drautb-pd-badges-rest-api",
"dsw88-test-dev",
"egglestonbd-beanstalk-dev",
"egglestonbd-beanstalk-dev-sample-web",
"eim-persistence2-dev",
"eim-persistence3-dev",
"elasticache-test-dev",
"fs-ckfinder-integration",
"jacoblj-postgres-sandboxtest",
"jalbr74-experiments-integration",
"jdbc-message-service-test",
"jfr8",
"jfre8",
"jfree-paas-tutorial-dev",
"jmason-paas-tutorial-dev",
"jwcranford-paas-tutorial-dev",
"kristeng-paas-tutorial-dev",
"leerobertw-paas-tutorial-dev",
"meme-generator-example-dev",
"michelles-validation-test-dynamodb-app",
"michelles-validation-test-mysqlrds-app",
"michelles-validation-test-pstgrssrds-app",
"michelles-validation-test-s3-aws-awesome",
"michelles-validation-test-s3-dc-dev-app",
"michelles-validation-test-sqsqueue-app",
"mikewright-aws-test-beta",
"pgs-dev",
"pipe-dpc-trove-development",
"pipe-storage-aws-finderws-development-store",
"pipe-storage-dax-s3-development-store",
"portfolio-parser-test",
"prof-dev-family-quiz-prod",
"professional-development-ramesbury-dev",
"qualification-rules-engine-aws-test",
"qualification-rules-engine-integration",
"qualification-rules-engine-staging",
"rdc-consumer-ws-pilot-sandbox",
"rdc-filemanager-pilot-sandbox",
"rdc-ingester-ws-pilot-sandbox",
"rdc-storage-rafs-pilot-sandbox",
"rdc-test-consumer-ws",
"rdc-test-ingester-ws",
"rdc-test-ws",
"rdc-ws-pilot-sandbox",
"Research-Eureka-Eureka-dockerbeta",
"research-suggestions-dev",
"roskelleycj-test",
"rsbohn-paas-dev",
"slide-test-deployable-component-dev",
"slide-test-deployable-component-test-1",
"slide-test-deployable-component-test-2",
"slide-test-deployable-component-test-3",
"slide-test-migration-dev",
"slide-test-migration-test-1",
"slide-test-migration-test-2",
"slide-test-migration-test-3",
"spc-db-spc-ws-dev",
"sps-reference-activity-worker-dev-sps-activity-worker",
"sps-reference-decider-dev-sps-decider",
"SQS-AWS-prototype-dev",
"steckdk-paas-tutorial-dev",
"sysps-bpd-testapp-simple-app-app",
"test-data-service-dev",
"test-data-service-integration",
"thayneharmon-paas-tutorial-dev",
"tree-copier-beta",
"tree-copier-ftint",
"tree-copier-test",
"tree-data-staging-aws",
"tree-data-test",
"trk-ws-dev",
"tsrimahesh-paas-tutorial-dev",
"u2ms-staging",
"watch-staging",
"web-service-tools-beta",
"zoning-controller-consumer-ws-int",
"zoning-controller-ws-int",
"zoning-filemanager-integration",
"zoning-spc-db-integration",
"zoning-zrafs-integration"
]

beanstalk = AWS::ElasticBeanstalk::Client.new

APPS_TO_DELETE.each do |app_name|
  puts "Deleting Application: #{app_name}"
  beanstalk.delete_application({:application_name => app_name, :terminate_env_by_force => true})
end