#!/usr/bin/env ruby

require "aws-sdk"

STACKS_TO_DELETE = [
  "service-sqsqueue-user-messaging-snippetqueuefh5",
  "service-sqsqueue-user-messaging-service-routes-snippetqueuefh5",
  "service-sqsqueue-SQS-AWS-prototype-dkf-protoq-dev-2",
  "service-sqsqueue-SQS-AWS-prototype-dkf-protoq-dev-1",
  "service-sqsqueue-SQS-AWS-prototype-dkf-protoq-dev",
  "service-sqsqueue-roskelleycj-bpd-testapp-dev-sqs-delete",
  "service-sqsqueue-patron-messaging-service-snippetqueuefh5",
  "service-sqsqueue-paas-maintenance-service-dev-paas-ms-queue",
  "service-sqsqueue-paas-maintenance-service-dev-job-queue",
  "service-sqsqueue-paas-cloudwatch-notifier-beta-queue",
  "service-sqsqueue-meme-generator-example-meme-sqs-dev",
  "service-sqsqueue-hazelcast-experiment-bd-testapp-dev-sqs-put",
  "service-sqsqueue-hazelcast-experiment-bd-testapp-dev-sqs-delete",
  "service-sqsqueue-common-notification-service-cns-sqs-dev",
  "service-sqsqueue-bpd-testapp-bpd-dev-sqs-put",
  "service-sqsqueue-bpd-testapp-bpd-dev-sqs-delete",
  "service-sqsqueue-booklet-orchestration-bos-queue-dev",
  "service-sqsqueue-booklet-orchestration-bos-queue-beta",
  "service-s3bucket-zoning-zrafs-zrafs-s3-int",
  "service-s3bucket-zoning-rafs-zoning-rafs-sandbox",
  "service-s3bucket-zoning-filemanager-zfilemanager-s3-int",
  "service-s3bucket-zoning-components-zoning-rafs-sandbox",
  "service-s3bucket-zoning-components-workingstore-sandbox",
  "service-s3bucket-test-data-webapp-TestDataS3",
  "service-s3bucket-sysps-s3aws-barclays-s3aws-sauce",
  "service-s3bucket-sysps-roskelleycj-s3aws-sauce",
  "service-s3bucket-pipe-storage-s3-storage-dev-s3-bucket",
  "service-s3bucket-pipe-storage-s3-dev-dax-bucket",
  "service-s3bucket-pipe-storage-s3-dax-bucket-service",
  "service-s3bucket-pipe-storage-s3-buckets-storage-dev-s3bucket",
  "service-s3bucket-pipe-storage-dax-s3-dev-dax-bucket",
  "service-s3bucket-pipe-storage-aws-finderws-dev-das-bucket",
  "service-s3bucket-pgs-pgs-bucket-dev",
  "service-s3bucket-nicholasterry-tst11-s3cret-sauce",
  "service-s3bucket-nicholasterry-tst10-s3cret-sauce",
  "service-s3bucket-nicholasterry-test-s3cret-sauce",
  "service-s3bucket-nicholasterry-test9-s3cret-sauce",
  "service-s3bucket-nicholasterry-test8-s3cret-sauce",
  "service-s3bucket-nicholasterry-test7-s3cret-sauce",
  "service-s3bucket-nicholasterry-nterry-test-s3cret-sauce",
  "service-s3bucket-nicholasterry-kill9-s3cret-sauce",
  "service-s3bucket-nicholasterry-foo-s3cret-sauce",
  "service-s3bucket-nicholasterry-foo-LD-s3cret-sauce",
  "service-s3bucket-my-family-booklet-mfb-s3-dev",
  "service-s3bucket-my-family-booklet-mfb-s3-beta-2",
  "service-s3bucket-michelles-validation-test-s3-dc-itsbouquetnotbucket",
  "service-s3bucket-michelles-validation-test-s3-aws-sauce",
  "service-s3bucket-meme-generator-example-meme-s3-dev",
  "service-s3bucket-fs-ckfinder-store-integration",
  "service-s3bucket-fs-ckfinder-store-beta",
  "service-s3bucket-eim-workflow-service-eim-wfs-s3",
  "service-s3bucket-eim-workflow-service-eim-s3",
  "service-s3bucket-egglestonbd-beanstalk-s3-bucket-a",
  "service-s3bucket-dps-s3generate-dps-s3generate",
  "service-s3bucket-callla-paas-tut-fs-callla-paas-tut2",
  "service-s3bucket-bpd-testapp-bpd-s3cret-sauce",
  "service-s3bucket-booklet-service-booklet-s3-dev",
  "service-s3bucket-booklet-service-booklet-s3-beta",
  "service-s3bucket-blueprint-deploy-acceptance-s3cret-sauce",
  "service-redis-leerobertw-paas-tutorial-apiredis",
  "service-postgresrds-tsrimahesh-paas-tutorial-tsrimahesh-paas-db",
  "service-postgresrds-trk-ws-trk-db-dev",
  "service-postgresrds-trk-ws-db-dev",
  "service-postgresrds-slide-test-deployable-component-test-3-postgres",
  "service-postgresrds-slide-test-deployable-component-test-2-postgres",
  "service-postgresrds-slide-test-deployable-component-test-1-postgres",
  "service-postgresrds-slide-test-deployable-component-dev-postgres",
  "service-postgresrds-slide-test-datacenter-to-aws-aws-test-zoo-database",
  "service-postgresrds-scope-service-scopeservice-dev",
  "service-postgresrds-scope-service-scopeservice-beta",
  "service-postgresrds-professional-development-ramesbury-pdr-dev-rds",
  "service-postgresrds-pgs-pgs-rds-dev",
  "service-postgresrds-patron-messaging-service-ums-rds-dev",
  "service-postgresrds-paas-domain-traffic-manager-pkdev-rds",
  "service-postgresrds-paas-domain-traffic-manager-dtm-conf-dev",
  "service-postgresrds-paas-domain-traffic-manager-dtm-conf-dbs",
  "service-postgresrds-paas-aws-platform-demo-app-dev-database",
  "service-postgresrds-NuevOSS-DB-oss-nuevoss-rds-db",
  "service-postgresrds-nge-rest-prod-db",
  "service-postgresrds-my-family-booklet-mfb-rds-dev",
  "service-postgresrds-my-family-booklet-mfb-rds-beta",
  "service-postgresrds-lowryda-abuse-framework-1-dev-rds",
  "service-postgresrds-kinsersh-test-database",
  "service-postgresrds-jdbc-message-service-rds-test",
  "service-postgresrds-jdbc-message-service-rds-integration",
  "service-postgresrds-jacoblj-postgres-dev-rds",
  "service-postgresrds-fs-sas-node-test-rds-dev",
  "service-postgresrds-eim-workflow-service-eimdb-rds-dev",
  "service-postgresrds-eim-web-eim-rds-dev",
  "service-postgresrds-eim-persistence-rds-dev",
  "service-postgresrds-eim-persistence-eim-rds-dev",
  "service-postgresrds-eim-persistence-eimdb-rds-dev-1",
  "service-postgresrds-eim-persistence-eimdb-rds-dev",
  "service-postgresrds-eim-persistence-eimdb9-rds-dev",
  "service-postgresrds-eim-persistence-eimdb8-rds-dev",
  "service-postgresrds-eim-persistence-eimdb7-rds-dev",
  "service-postgresrds-eim-persistence-eimdb6-rds-dev",
  "service-postgresrds-eim-persistence-eimdb5-rds-dev",
  "service-postgresrds-eim-persistence-eimdb4-rds-dev",
  "service-postgresrds-eim-persistence-eimdb3-rds-dev",
  "service-postgresrds-eim-persistence-eimdb32-rds-dev",
  "service-postgresrds-eim-persistence-eimdb31-rds-dev",
  "service-postgresrds-eim-persistence-eimdb30-rds-dev",
  "service-postgresrds-eim-persistence-eimdb29-rds-dev",
  "service-postgresrds-eim-persistence-eimdb28-rds-dev",
  "service-postgresrds-eim-persistence-eimdb27-rds-dev",
  "service-postgresrds-eim-persistence-eimdb26-rds-dev",
  "service-postgresrds-eim-persistence-eimdb25-rds-dev",
  "service-postgresrds-eim-persistence-eimdb24-rds-dev",
  "service-postgresrds-eim-persistence-eimdb23-rds-dev",
  "service-postgresrds-eim-persistence-eimdb22-rds-dev",
  "service-postgresrds-eim-persistence-eimdb21-rds-dev",
  "service-postgresrds-eim-persistence-eimdb20-rds-dev",
  "service-postgresrds-eim-persistence-eimdb19-rds-dev",
  "service-postgresrds-eim-persistence-eimdb18-rds-dev",
  "service-postgresrds-eim-persistence-eimdb17-rds-dev",
  "service-postgresrds-eim-persistence-eimdb16-rds-dev",
  "service-postgresrds-eim-persistence-eimdb15-rds-dev",
  "service-postgresrds-eim-persistence-eimdb14-rds-dev",
  "service-postgresrds-eim-persistence-eimdb13-rds-dev",
  "service-postgresrds-eim-persistence-eimdb12-rds-dev",
  "service-postgresrds-eim-persistence-eimdb11-rds-dev",
  "service-postgresrds-eim-persistence-eimdb10-rds-dev",
  "service-postgresrds-eim-persistence3-eim3db10-rds-dev",
  "service-postgresrds-crx-db-stage",
  "service-postgresrds-crx-db-dev",
  "service-postgresrds-cds-rds-pg-pgrds-shard2",
  "service-postgresrds-cds-rds-pg-pgrds-shard1",
  "service-postgresrds-cds-rds-pg-pgrds-master",
  "service-postgresrds-campaign-api2-campaign-rds-dev",
  "service-postgresrds-callla-paas-tut-fs-callla-paas-tut-rds",
  "service-postgresrds-build-badger-dev-rds",
  "service-postgresrds-brb-changes-consumer-service-brbcc-rds-dev",
  "service-postgresrds-brb-changes-consumer-service-brbcc-rds",
  "service-postgresrds-bpd-testapp-bpd-dev-postgresrds",
  "service-postgresrds-booklet-service-booklet-rds-dev",
  "service-postgresrds-booklet-service-booklet-rds-beta",
  "service-postgresrds-bml-paas-tutorial-bmlTestRDS",
  "service-postgresrds-benjaminlimb-paas-tutorial-blimbTestRDS",
  "service-postgresrds-admin-queue-service-aqs-rds-test",
  "service-postgresrds-admin-label-service-rds-test",
  "service-postgresrds-admin-label-service-rds-integration",
  "service-mysqlrds-zoning-controller-int-db",
  "service-mysqlrds-zoning-controller-db-pilot-sandbox",
  "service-mysqlrds-zoning-controller-db-beta-zdc",
  "service-mysqlrds-trk-ws-db-dev-mysql",
  "service-mysqlrds-start-rds-soi-sandbox",
  "service-mysqlrds-start-rds-soi-integration",
  "service-mysqlrds-start-rds-soi",
  "service-mysqlrds-slide-test-migration-test-3-rds",
  "service-mysqlrds-slide-test-migration-test-2-rds",
  "service-mysqlrds-slide-test-migration-test-1-rds",
  "service-mysqlrds-slide-test-migration-dev-rds",
  "service-mysqlrds-slide-test-deployable-component-webapp-rds",
  "service-mysqlrds-slide-test-deployable-component-test-3-rds",
  "service-mysqlrds-slide-test-deployable-component-test-2-rds",
  "service-mysqlrds-slide-test-deployable-component-test-1-rds",
  "service-mysqlrds-slide-test-deployable-component-rds",
  "service-mysqlrds-slide-test-deployable-component-dev-rds",
  "service-mysqlrds-scope-service-soi-integration",
  "service-mysqlrds-scope-service-soi-beta",
  "service-mysqlrds-scope-service-rds-soi-integration",
  "service-mysqlrds-scope-alerts-foundation-alert-int",
  "service-mysqlrds-idx-workflow-rds-integration",
  "service-mysqlrds-idx-template-app-rds-integration",
  "service-mysqlrds-idx-statistic-rds-integration",
  "service-mysqlrds-idx-orchestration-rds-integration",
  "service-mysqlrds-idx-metric-rds-integration",
  "service-mysqlrds-idx-message-rds-integration",
  "service-mysqlrds-idx-api-app-rds-wf-integration",
  "service-mysqlrds-idx-api-app-rds-api-integration",
  "service-mysqlrds-community-volunteer-beta-volunteer-rds",
  "service-mysqlrds-community-ask-aws-beta-aws-rds",
  "service-mysqlrds-common-notification-service-cns-rds-dev",
  "service-mysqlrds-brb-tester-service-brbt-rds-dev",
  "service-mysqlrds-bpd-testapp-bpd-dev-mysqlrds",
  "service-mysqlrds-beanstalk-dev-rds-charset",
  "service-mysqlrds-alerts-fs-foundation-alert-sandbox",
  "service-mysqlrds-alerts-fs-alerts-sandbox",
  "service-mysqlrds-alerts-foundation-alert-integration",
  "service-mysqlrds-alerts-foundation-alert-int",
  "service-memcached-elasticache-test-my-service",
  "service-memcached-bpd-testapp-bpd-dev-memcached",
  "service-memcached-acceptance-test-app-pbxq6S-bpd-dev-memcached",
  "service-dynamodbtable-research-suggestions-dev-dynamodb",
  "service-dynamodbtable-paas-dlb-status-dblstatus",
  "service-dynamodbtable-paas-cloudwatch-notifier-development-dynamodb",
  "service-dynamodbtable-meme-generator-example-meme-dynamodb-dev",
  "service-dynamodbtable-egglestonbd-bpd-testapp-dev-dynamodb",
  "service-dynamodbtable-dynamodb-sandbox-dynamodbsandbox",
  "service-dynamodbtable-bpd-testapp-bpd-dev-dynamodb",
  "service-dynamodbtable-alfy-paas-tutorial-dev-dynamodb",
  "service-cassandra-barrettford-blueprint-deploy-test-dev-cassandra",
  "ps-temp-service-roles",
  "ps-sqs-temp-pubsub",
  "ps-sqs-pubsub-verifier",
  "ps-sqs-ms-testapp-put-queue",
  "ps-sqs-ms-testapp-delete-queue",
  "ps-sqs-bpd-testapp-put-queue",
  "ps-sqs-bpd-testapp-delete-queue",
  "ps-postgresrds-package-deploy-database",
  "ps-postgresrds-ms-testapp-postgres-db",
  "ps-postgresrds-al-rds-test",
  "ps-postgresrds-admin-label-service-rds-test",
  "ps-postgresrds-admin-label-service-db-test",
  "ps-postgresrds-admin-label-service-db-integration",
  "ps-mysqlrds-ms-testapp-mysql-db",
  "ps-mysqlrds-bpd-testapp-mysql-db",
  "ps-dynamodbtable-ms-testapp-dynamodb-table",
  "ps-dynamodbtable-bpd-testapp-dynamodb-table",
  "ps-cassandra-cassandra-testapp-rname",
  "ps-beanstalk-sg-zoning-zrafs-integration",
  "ps-beanstalk-sg-zoning-filemanager-integration",
  "ps-beanstalk-sg-zoning-controller-ws-sandbox",
  "ps-beanstalk-sg-zoning-controller-ws-int",
  "ps-beanstalk-sg-zoning-controller-consumer-ws-pilot-sandbox",
  "ps-beanstalk-sg-zoning-controller-consumer-ws-int",
  "ps-beanstalk-sg-zoning-components-zoning-rafs-beta",
  "ps-beanstalk-sg-zoning-components-zoning-filemanager-beta",
  "ps-beanstalk-sg-web-service-tools-beta",
  "ps-beanstalk-sg-u2ms-staging",
  "ps-beanstalk-sg-u2ms-rwh-dev-app",
  "ps-beanstalk-sg-tsrimahesh-paas-tutorial-dev",
  "ps-beanstalk-sg-trk-ws-dev",
  "ps-beanstalk-sg-tree-data-test",
  "ps-beanstalk-sg-tree-data-staging-aws",
  "ps-beanstalk-sg-tree-copier-test",
  "ps-beanstalk-sg-tree-copier-beta",
  "ps-beanstalk-sg-thayneharmon-paas-tutorial-dev",
  "ps-beanstalk-sg-test-data-service-integration",
  "ps-beanstalk-sg-test-data-service-dev",
  "ps-beanstalk-sg-sysps-bpd-testapp-swf-workers",
  "ps-beanstalk-sg-sysps-bpd-testapp-simple-app-app",
  "ps-beanstalk-sg-sysps-bpd-testapp-pstgrssrds-app",
  "ps-beanstalk-sg-steckdk-paas-tutorial-dev",
  "ps-beanstalk-sg-sqs-sas-consumer-verifier-test-service",
  "ps-beanstalk-sg-SQS-AWS-prototype-dev",
  "ps-beanstalk-sg-sps-reference-decider-dev-sps-decider",
  "ps-beanstalk-sg-sps-reference-activity-worker-dev-sps-activity-worker",
  "ps-beanstalk-sg-sps-cassandra-testapp-cassandra-dev-app",
  "ps-beanstalk-sg-slide-test-migration-test-3",
  "ps-beanstalk-sg-slide-test-migration-test-2",
  "ps-beanstalk-sg-slide-test-migration-test-1",
  "ps-beanstalk-sg-slide-test-migration-dev",
  "ps-beanstalk-sg-slide-test-deployable-component-test-1",
  "ps-beanstalk-sg-slide-test-deployable-component-dev",
  "ps-beanstalk-sg-rsbohn-paas-dev",
  "ps-beanstalk-sg-research-suggestions-dev",
  "ps-beanstalk-sg-qualification-rules-engine-staging",
  "ps-beanstalk-sg-qualification-rules-engine-integration",
  "ps-beanstalk-sg-qualification-rules-engine-aws-test",
  "ps-beanstalk-sg-professional-development-ramesbury-dev",
  "ps-beanstalk-sg-prof-dev-family-quiz-prod",
  "ps-beanstalk-sg-portfolio-parser-test",
  "ps-beanstalk-sg-pipe-storage-aws-finderws-development-store",
  "ps-beanstalk-sg-pipe-dpc-trove-development",
  "ps-beanstalk-sg-pgs-dev",
  "ps-beanstalk-sg-paas-swf-dlb-status-activity-worker-dev",
  "ps-beanstalk-sg-paas-sps-ssh-key-generator-sps-ssh-key-generator-workers",
  "ps-beanstalk-sg-paas-sps-s3-testapp-acceptance-app",
  "ps-beanstalk-sg-paas-sps-hello-world-testapp-hello-dev-app",
  "ps-beanstalk-sg-paas-sps-hello-world-sps-hello-world-workers",
  "ps-beanstalk-sg-paas-DTMtst-dev",
  "ps-beanstalk-sg-paas-DTM-test-dev",
  "ps-beanstalk-sg-paas-cassandra-testapp-cassandra-dev-app",
  "ps-beanstalk-sg-meme-generator-example-dev",
  "ps-beanstalk-sg-lindseyml-paas-tutorial-dev",
  "ps-beanstalk-sg-leerobertw-paas-tutorial-dev",
  "ps-beanstalk-sg-kristeng-paas-tutorial-dev",
  "ps-beanstalk-sg-jwcranford-paas-tutorial-dev",
  "ps-beanstalk-sg-jmason-paas-tutorial-dev",
  "ps-beanstalk-sg-jfree-paas-tutorial-dev",
  "ps-beanstalk-sg-jdbc-message-service-test",
  "ps-beanstalk-sg-jalbr74-experiments-integration",
  "ps-beanstalk-sg-jacoblj-postgres-sandboxtest",
  "ps-beanstalk-sg-hartleybd-paas-tutorial-elijah-app",
  "ps-beanstalk-sg-fs-sas-node-dev",
  "ps-beanstalk-sg-fs-ckfinder-integration",
  "ps-beanstalk-sg-elasticache-test-dev",
  "ps-beanstalk-sg-egglestonbd-beanstalk-dev-sample-web",
  "ps-beanstalk-sg-egglestonbd-beanstalk-dev",
  "ps-beanstalk-sg-dsw88-test-dev",
  "ps-beanstalk-sg-drautb-pd-badges-rest-api",
  "ps-beanstalk-sg-drautb-pd-badges-frontend-server",
  "ps-beanstalk-sg-dps-s3generate-dev",
  "ps-beanstalk-sg-davebrandt-paas-tutorial-dev",
  "ps-beanstalk-sg-ct-watchnotify-bridge-test",
  "ps-beanstalk-sg-ct-watchnotify-bridge-integration",
  "ps-beanstalk-sg-crx-stage",
  "ps-beanstalk-sg-crx-dev",
  "ps-beanstalk-sg-continuous-delivery-test-ruby-app-dev",
  "ps-beanstalk-sg-continuous-delivery-test-docker-app-dev",
  "ps-beanstalk-sg-cmisx-update-acceptance-tests",
  "ps-beanstalk-sg-bpd-testapp-sqsqueue",
  "ps-beanstalk-sg-bpd-testapp-simple-app",
  "ps-beanstalk-sg-bpd-testapp-s3bucket",
  "ps-beanstalk-sg-bpd-testapp-redis",
  "ps-beanstalk-sg-bpd-testapp-pstgrssrds",
  "ps-beanstalk-sg-bpd-testapp-mysqlrds",
  "ps-beanstalk-sg-bpd-testapp-memcached",
  "ps-beanstalk-sg-bpd-testapp-dynamodb",
  "ps-beanstalk-sg-booklet-service-dev",
  "ps-beanstalk-sg-booklet-pdf-dev",
  "ps-beanstalk-sg-booklet-orchestration-dev",
  "ps-beanstalk-sg-blueprint-deploy-u2ms-rwh-u2ms-rwh-d-app",
  "ps-beanstalk-sg-blueprint-deploy-u2ms-rwh-dev-app",
  "ps-beanstalk-sg-barclays-paas-test-dev",
  "ps-beanstalk-sg-at-node-test-dev",
  "ps-beanstalk-sg-assignment-service-integration",
  "ps-beanstalk-sg-assignment-service-assignment-service-test",
  "ps-beanstalk-sg-admin-queue-service-aqs-test",
  "ps-beanstalk-sg-admin-label-service-test",
  "ps-beanstalk-sg-admin-label-service-integration"
]

@cfn_client = AWS::CloudFormation::Client.new
@iam_client = AWS::IAM::Client.new
@s3 = AWS::S3.new

STACKS_TO_DELETE.each do |stack_name|
  sleep 2
  puts "\nDeleting stack #{stack_name}"

  puts "\tListing stack resources..."
  begin
    stack_summary = @cfn_client.describe_stacks({:stack_name => stack_name}).data[:stacks][0]

    if stack_summary[:stack_status] != "DELETE_FAILED"
      puts "STACK #{stack_name} has status #{stack_summary[:stack_status]}, skipping..."
      next
    end

    stack_resources = @cfn_client.list_stack_resources({:stack_name => stack_name}).data[:stack_resource_summaries]
    stack_resources.each do |stack_resource|

      puts "Checking resource: #{stack_resource}"

      # if stack_resource[:resource_type] == "AWS::IAM::Group"
      #   group_name = stack_resource[:physical_resource_id]
      #   puts "\tCleaning group: #{group_name}"
      #   group = @iam_client.get_group({:group_name => group_name})
      #   users = group[:users]
      #   users.each do |u|
      #     puts "\t\tDeleting user: #{u[:user_name]}"
      #     @iam_client.remove_user_from_group({:group_name => group_name, :user_name => u[:user_name]})

      #     access_keys_meta = @iam_client.list_access_keys({:user_name => u[:user_name]})[:access_key_metadata]
      #     access_keys_meta.each do |k|
      #       @iam_client.delete_access_key({:user_name => u[:user_name], :access_key_id => k[:access_key_id]})
      #     end

      #     @iam_client.delete_user({:user_name => u[:user_name]})
      #   end
      if stack_resource[:resource_type] == "AWS::S3::Bucket"
        bucket_name = stack_resource[:physical_resource_id]
        puts "Deleting all objects in #{bucket_name}"
        bucket = @s3.buckets[bucket_name] # makes no request
        bucket.objects.delete_all
      end

    end

    @cfn_client.delete_stack(:stack_name => stack_name)
  rescue => e

  end
end

